version: "3.9"

services:
  web:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run build && pnpm start"
    volumes:
      - /path/to/your/code:/app  # Ajuste este caminho
    environment:
      - NODE_ENV=production
    networks:
      - network_swarm_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.getbrain.rule=Host(`getbrain.com.br`, `www.getbrain.com.br`)"
        - "traefik.http.routers.getbrain.entrypoints=websecure"
        - "traefik.http.routers.getbrain.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.getbrain.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.www2root.redirectregex.regex=^https?://www\\.(.*)"
        - "traefik.http.middlewares.www2root.redirectregex.replacement=https://$$1"
        - "traefik.http.routers.getbrain.middlewares=www2root@docker"
        - "traefik.docker.network=network_swarm_public"
      restart_policy:
        condition: on-failure

networks:
  network_swarm_public:
    external: true
