services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # opcional: carregue variáveis do seu .env na raiz do repo
    # env_file:
    #   - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
