version: "3.9"

services:
  getbrain:
    image: ghcr.io/getbrainbrasil/getbrain-website:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - network_swarm_public            # mesmo nome da rede do Traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true

        # HTTP -> HTTPS (router no entrypoint web)
        - traefik.http.routers.gb-redirect.rule=Host(`getbrain.com.br`,`www.getbrain.com.br`)
        - traefik.http.routers.gb-redirect.entrypoints=web
        - traefik.http.middlewares.gb-https-redirect.redirectscheme.scheme=https
        - traefik.http.routers.gb-redirect.middlewares=gb-https-redirect@docker

        # HTTPS (router principal)
        - traefik.http.routers.gb-https.rule=Host(`getbrain.com.br`,`www.getbrain.com.br`)
        - traefik.http.routers.gb-https.entrypoints=websecure
        - traefik.http.routers.gb-https.tls=true
        - traefik.http.routers.gb-https.tls.certresolver=letsencryptresolver

        # Canonical: www -> sem www (mantenha OU troque conforme preferir)
        - traefik.http.middlewares.gb-www.redirectregex.regex=^https?://www\\.(.*)
        - traefik.http.middlewares.gb-www.redirectregex.replacement=https://$${1}
        - traefik.http.routers.gb-https.middlewares=gb-www@docker

        # Service (porta interna do Next)
        - traefik.http.services.gb-svc.loadbalancer.server.port=3000

        # REDE onde o Traefik vai alcançar este serviço (igual à Evolution)
        - traefik.docker.network=network_swarm_public

    # (Opcional) healthcheck simples
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  network_swarm_public:
    external: true
